package dds.pantallas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*package dds.pantallas;*/
import dds.excepcionesInterfaz.LongitudesMaximasException;
import dds.dtos.BedelDTO;
import dds.enumerados.Turno;
import dds.excepcionesLogicas.BedelNoEncontradoException;
import dds.gestores.GestorBedel;
import java.awt.Component;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.FocusTraversalPolicy;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jlcla
 */
public class BuscarBedel extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private ArrayList<BedelDTO> listaBedel = new ArrayList<>();
    /**
     * Creates new form BuscarBedel
     */
    public BuscarBedel() {
        initComponents();
        // Crear un modelo con las columnas deseadas y celdas no editables
        modelo = new DefaultTableModel(new Object[][] {}, new String[] {
            "Apellido", "Nombre", "Turno", "ID"
        }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hace que ninguna celda sea editable
            }
        };
        TablaResultados.setModel(modelo);
        configurarTabulacion(); 
    }
    private void configurarTabulacion() {
        // Configuramos una política de tabulación personalizada
        setFocusTraversalPolicy(new FocusTraversalPolicy() {
            @Override
            public Component getComponentAfter(Container container, Component component) {
                if (component.equals(ApellidoBedel)) return TurnosBedel;
                if (component.equals(TurnosBedel)) return Buscar;
                if (component.equals(Buscar)) return Cancelar;
                if (component.equals(Cancelar)) return Editar;
                if (component.equals(Editar)) return Eliminar;
                return ApellidoBedel; // Vuelve al primero después del último
            }

            @Override
            public Component getComponentBefore(Container container, Component component) {
                if (component.equals(Eliminar)) return Editar;
                if (component.equals(Editar)) return Cancelar;
                if (component.equals(Cancelar)) return Buscar;
                if (component.equals(Buscar)) return TurnosBedel;
                if (component.equals(TurnosBedel)) return ApellidoBedel;
                return Eliminar; // Vuelve al último antes del primero
            }

            @Override
            public Component getDefaultComponent(Container container) {
                return ApellidoBedel; // El componente inicial es "ApellidoBedel"
            }

            @Override
            public Component getFirstComponent(Container container) {
                return ApellidoBedel; // Primer componente del ciclo
            }

            @Override
            public Component getLastComponent(Container container) {
                return Eliminar; // Último componente del ciclo
            }
        });

        // Opcional: Aseguramos que el foco inicial esté en "ApellidoBedel"
        SwingUtilities.invokeLater(() -> ApellidoBedel.requestFocusInWindow());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ApellidoBedel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TurnosBedel = new javax.swing.JComboBox<>();
        Buscar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        Eliminar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        NavegacionMenuAdmin = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Bedel"));
        jPanel1.setToolTipText("");

        jLabel2.setText("Apellido");

        ApellidoBedel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoBedelActionPerformed(evt);
            }
        });

        jLabel4.setText("Turno en el que trabaja");

        TurnosBedel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Mañana", "Tarde", "Noche" }));
        TurnosBedel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurnosBedelActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Cancelar.setBackground(new java.awt.Color(255, 255, 153));
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancelar)
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ApellidoBedel)
                    .addComponent(TurnosBedel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(305, 305, 305))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidoBedel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TurnosBedel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Buscar))
                .addGap(15, 15, 15))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Resultados"));
        jPanel2.setToolTipText("");

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellido", "Nombre", "Turno", "ID"
            }
        ));
        jScrollPane1.setViewportView(TablaResultados);

        Eliminar.setBackground(new java.awt.Color(255, 153, 153));
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editar)
                    .addComponent(Eliminar))
                .addContainerGap())
        );

        NavegacionMenuAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionMenuAdmin.setForeground(new java.awt.Color(51, 51, 255));
        NavegacionMenuAdmin.setText("Menú Administrador");
        NavegacionMenuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavegacionMenuAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavegacionMenuAdminMouseEntered(evt);
            }
        });

        jLabel22.setText(">");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Buscar Bedel");

        jLabel23.setText(">");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NavegacionMenuAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(275, 275, 275)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel22)
                    .addComponent(NavegacionMenuAdmin)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TurnosBedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurnosBedelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TurnosBedelActionPerformed
    
    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed

        try {
            // Limpiar la tabla antes de agregar nuevos datos
            modelo.setRowCount(0);

            // Obtener el turno seleccionado
            String turno = TurnosBedel.getSelectedItem().toString();
            Turno t = null;
            
            if (!turno.equals("<Seleccione>")) t = Turno.valueOf(turno);
            
            if (ApellidoBedel.getText().length() > 50) throw new LongitudesMaximasException();

            // Obtener la lista de BedelDTO desde GestorBedel
            listaBedel = GestorBedel.getInstance().busqueda(ApellidoBedel.getText(),t);

            // Iterar sobre la lista y agregar las filas al modelo
            for (BedelDTO b : listaBedel) {
                Object[] bedel = new Object[4];
                bedel[0] = b.getApellido();
                bedel[1] = b.getNombre();
                bedel[2] = b.getTurno();
                bedel[3] = b.getIdUsuario();
                modelo.addRow(bedel);
            }

            TablaResultados.setModel(modelo);
        } catch (LongitudesMaximasException e) {
            JOptionPane.showMessageDialog(null, "Error: longitud maxima de algun campo excedida", "registro", JOptionPane.ERROR_MESSAGE);
        }



            
    }//GEN-LAST:event_BuscarActionPerformed
    
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú Administrador?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();

            // Regresar al menú admin
            MenuAdmin ma = new MenuAdmin();
            ma.setVisible(true);
        }
    }//GEN-LAST:event_CancelarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed

        int filaSeleccionada = TablaResultados.getSelectedRow(); // Obtener la fila seleccionada
        int opcion;
        if (filaSeleccionada!=-1){ 
            opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de editar el bedel?",
                "Confirmar modificacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );
            if (opcion == JOptionPane.YES_OPTION) {
                this.setVisible(false);
                new ModificarBedel(listaBedel.get(filaSeleccionada), this, filaSeleccionada).setVisible(true);
            }
        }else {
            JOptionPane.showMessageDialog(this, "No selecciono un bedel", "Error de seleccion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int filaSeleccionada = TablaResultados.getSelectedRow(); // Obtener la fila seleccionada
        
        if (filaSeleccionada!=-1){ 
            boolean opcion = new ConfirmarEliminacionBedel(this, listaBedel.get(filaSeleccionada)).getOpcion();
            if(opcion){
                DefaultTableModel modelo = (DefaultTableModel) TablaResultados.getModel();
                try {
                    GestorBedel.getInstance().eliminacionLogica(listaBedel.get(filaSeleccionada).getId());
                    // Eliminar la fila del modelo
                    modelo.removeRow(filaSeleccionada);
                    JOptionPane.showMessageDialog(this, "Bedel eliminado exitosamente");
                    TablaResultados.setModel(modelo);
                }catch (BedelNoEncontradoException ex) {
                    Logger.getLogger(BuscarBedel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else {
            JOptionPane.showMessageDialog(this, "No selecciono un bedel", "Error de seleccion", JOptionPane.ERROR_MESSAGE);
        }        
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void ApellidoBedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoBedelActionPerformed
        
    }//GEN-LAST:event_ApellidoBedelActionPerformed

    private void NavegacionMenuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionMenuAdminMouseClicked
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú Administrador?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();

            // Regresar al menú
            MenuAdmin ma = new MenuAdmin();
            ma.setVisible(true);
        }
    }//GEN-LAST:event_NavegacionMenuAdminMouseClicked

    private void NavegacionMenuAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionMenuAdminMouseEntered
        NavegacionMenuAdmin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NavegacionMenuAdminMouseEntered



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoBedel;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel NavegacionMenuAdmin;
    private javax.swing.JTable TablaResultados;
    private javax.swing.JComboBox<String> TurnosBedel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void modificarTabla(BedelDTO bdto, int filaSeleccionada) {
        DefaultTableModel modelo = (DefaultTableModel) this.TablaResultados.getModel();
        modelo.setValueAt(bdto.getApellido(), filaSeleccionada, 0);
        modelo.setValueAt(bdto.getNombre(), filaSeleccionada, 1);
        modelo.setValueAt(bdto.getTurno().toString(), filaSeleccionada, 2);
        modelo.setValueAt(bdto.getIdUsuario(), filaSeleccionada, 3);
    }
    public ArrayList<BedelDTO> getListaBedel(){
        return this.listaBedel;        
    }
    
}
