/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dds.pantallas;

import dds.excepcionesInterfaz.OpcionNoSeleccionadaException;
import dds.excepcionesInterfaz.CamposObligatoriosVaciosException;
import dds.excepcionesInterfaz.LongitudesMaximasException;
import dds.excepcionesLogicas.ContraseñaEquivocadaException;
import dds.excepcionesLogicas.UsuarioInexistenteException;
import dds.gestores.GestorBedel;
import dds.gestores.GestorContraseña;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jlcla
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        buttonGroup1.add(Administrador);
        buttonGroup1.add(Bedel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Administrador = new javax.swing.JRadioButton();
        Bedel = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        IdUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoContrasena = new javax.swing.JPasswordField();
        verPW = new javax.swing.JCheckBox();
        IniciarSesion = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Inicio de Sesión"));

        Administrador.setText("Administrador");

        Bedel.setText("Bedel");
        Bedel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedelActionPerformed(evt);
            }
        });

        jLabel2.setText("Id Usuario");

        jLabel5.setText("Contraseña");

        CampoContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoContrasenaActionPerformed(evt);
            }
        });

        verPW.setText("Ver contraseña");
        verPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPWActionPerformed(evt);
            }
        });

        IniciarSesion.setText("Iniciar Sesión");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(255, 255, 153));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CampoContrasena)
                    .addComponent(IdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verPW)
                .addGap(261, 261, 261))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(Administrador)
                        .addGap(64, 64, 64)
                        .addComponent(Bedel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verPW)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Administrador)
                    .addComponent(Bedel))
                .addGap(35, 35, 35)
                .addComponent(IniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salir)
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        try{
            iniciarSesion(IdUsuario.getText());
        }
        catch (CamposObligatoriosVaciosException ex){
            JOptionPane.showMessageDialog(null, "Error: hay un campo vacío", "Sesion", JOptionPane.ERROR_MESSAGE);
        }
        catch (OpcionNoSeleccionadaException ex){
            JOptionPane.showMessageDialog(null, "Error: por favor elija si es Administrador o Bedel", "Sesion", JOptionPane.ERROR_MESSAGE);
        }
        catch (UsuarioInexistenteException | ContraseñaEquivocadaException ex){
            JOptionPane.showMessageDialog(null, "Error: usuario o contraseña invalida", "Sesion", JOptionPane.ERROR_MESSAGE);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeySpecException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LongitudesMaximasException ex) {
            JOptionPane.showMessageDialog(null, "Error: longitud maxima de algun campo excedida", "Sesion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_IniciarSesionActionPerformed
    private void iniciarSesion(String usuario) throws UsuarioInexistenteException, CamposObligatoriosVaciosException, ContraseñaEquivocadaException, NoSuchAlgorithmException, InvalidKeySpecException, OpcionNoSeleccionadaException, LongitudesMaximasException{
        
        //---------------------------------------------------------------------------------------------------------------------------------------
        //VALIDACIONES:
        if (!Administrador.isSelected() && !Bedel.isSelected()) throw new OpcionNoSeleccionadaException();
        //Campos vacios:
        if("".equals(IdUsuario.getText()) || "".equals(CampoContrasena.getText())) throw new CamposObligatoriosVaciosException();
        if (IdUsuario.getText().length()>50 || CampoContrasena.getText().length()>50) throw new LongitudesMaximasException();
        
        //---------------------------------------------------------------------------------------------------------------------------------------
        boolean adminObedel;
        //admin es true, bedel es false
        if (Administrador.isSelected()){
            adminObedel=true;
            //Validar inicio de sesion:
            GestorContraseña.getInstance().login(IdUsuario.getText(),CampoContrasena.getText(),adminObedel);
            //ir al menu admin
            this.setVisible(false);
            this.dispose();

            // Abrir el nuevo menú
            MenuAdmin nuevoMenu = new MenuAdmin();
            nuevoMenu.setVisible(true);
        } else if (Bedel.isSelected()){
            adminObedel=false;
            //Validar inicio de sesion:
            GestorContraseña.getInstance().login(IdUsuario.getText(),CampoContrasena.getText(),adminObedel);
            //ir al menu bedel
            this.setVisible(false);
            this.dispose();
            // Abrir el nuevo menú
            MenuBedel nuevoMenu = new MenuBedel(usuario);
            nuevoMenu.setVisible(true);
        } 
        
    }
    
    private void CampoContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoContrasenaActionPerformed

    private void verPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPWActionPerformed
        if (evt.getSource() == verPW) {
            if (verPW.isSelected()) {
                // Si está seleccionado, mostrar la contraseña
                CampoContrasena.setEchoChar((char) 0);
            } else {
                // Si no está seleccionado, ocultar la contraseña
                CampoContrasena.setEchoChar('•');
            }
        }
    }//GEN-LAST:event_verPWActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // Mostrar cuadro de confirmación
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas salir?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        // Si el usuario confirma, cerrar el programa
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose(); // Cierra la ventana
            System.exit(0);  // Finaliza el programa
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void BedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BedelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Administrador;
    private javax.swing.JRadioButton Bedel;
    private javax.swing.JPasswordField CampoContrasena;
    private javax.swing.JTextField IdUsuario;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JButton Salir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox verPW;
    // End of variables declaration//GEN-END:variables
}
