/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dds.pantallas;

import dds.dtos.EsporadicaItemDTO;
import dds.dtos.PeriodicaItemDTO;
import dds.dtos.ReservaDTO;
import dds.dtos.ReservaMinimoSolapamientoDTO;
import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro Salvano
 */
public class MostrarReservasSolapadas extends javax.swing.JFrame {
    private List<ReservaDTO> reservas;
    EsporadicaItemDTO ei;
    PeriodicaItemDTO pi;
    /**
     * Creates new form MostrarReservasSolapadas
     * @param reservas
     * @param ei
     */
    public MostrarReservasSolapadas(List<ReservaDTO> reservas, EsporadicaItemDTO ei) {
        initComponents();
        this.reservas = reservas;
        this.ei=ei;
        llenarTabla();
        fijarTabulacionEnCancelar();
    }
    public MostrarReservasSolapadas(List<ReservaDTO> reservas, PeriodicaItemDTO pi) {
        initComponents();
        this.reservas = reservas;
        this.pi=pi;
        llenarTabla();
        fijarTabulacionEnCancelar();        
    }
    private void fijarTabulacionEnCancelar() {
        // Configuramos una política de tabulación que siempre apunte al botón "Cancelar"
        setFocusTraversalPolicy(new FocusTraversalPolicy() {
            @Override
            public Component getComponentAfter(Container container, Component component) {
                return Cerrar; // Siempre regresa al botón "Cancelar"
            }

            @Override
            public Component getComponentBefore(Container container, Component component) {
                return Cerrar; // Siempre regresa al botón "Cancelar"
            }

            @Override
            public Component getDefaultComponent(Container container) {
                return Cerrar; // El botón "Cancelar" tendrá el foco por defecto
            }

            @Override
            public Component getFirstComponent(Container container) {
                return Cerrar; // El primer componente es "Cancelar"
            }

            @Override
            public Component getLastComponent(Container container) {
                return Cerrar; // El último componente también es "Cancelar"
            }
        });
            // Aseguramos que el foco inicial esté en el botón "Cancelar"
        SwingUtilities.invokeLater(() -> Cerrar.requestFocusInWindow());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        Cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Autor de la reserva", "Catedra-Seminario-Curso", "Correo Electronico", "Inicio de la reserva", "Fin de la reserva"
            }
        ));
        jScrollPane1.setViewportView(TablaResultados);

        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ADVERTENCIA! Su reserva se solapa con la/s siguiente/s reserva/s:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Cerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cerrar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JTable TablaResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    private void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[][] {}, new String[] {
            "Autor De La Reserva", "Catedra-Seminario-Curso", "CorreoElectronico", "Inicio de la Reserva", "Fin de la Reserva"
        }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hace que ninguna celda sea editable
            }
        };
        
        for (ReservaDTO r : reservas) {
            if (!r.isEsporadica()){
                for(PeriodicaItemDTO i: r.getItemsPeriodica()){
                Object[] reserva = new Object[5];
                reserva[0] = r.getNombreapellidodocente();
                reserva[1] = r.getIdCurso();
                reserva[2] = r.getMailDeContacto();
                reserva[3] = i.getHorario();
                reserva[4] = i.getHoraFin();   
                modelo.addRow(reserva);
                }
            }else {
                for(EsporadicaItemDTO i: r.getItemsEsporadica()){
                Object[] reserva = new Object[5];
                reserva[0] = r.getNombreapellidodocente();
                reserva[1] = r.getIdCurso();
                reserva[2] = r.getMailDeContacto();
                reserva[3] = i.getHorario();
                reserva[4] = i.getHoraFin();   
                modelo.addRow(reserva);
                }
            }        
        }    
        TablaResultados.setModel(modelo);
    }

}
