/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dds.pantallas;

import dds.excepcionesInterfaz.DuracionCeroException;
import dds.excepcionesInterfaz.MultiploDe30Exception;
import dds.excepcionesInterfaz.HorarioFueraDeRangoException;
import dds.excepcionesInterfaz.DuracionExcedidaException;
import dds.excepcionesInterfaz.NoHayAulasDisponiblesException;
import dds.excepcionesInterfaz.CamposObligatoriosVaciosException;
import dds.dtos.AulaDTO;
import dds.dtos.EsporadicaItemDTO;
import dds.dtos.PeriodicaItemDTO;
import dds.dtos.ReservaDTO;
import dds.dtos.ReservaMinimoSolapamientoDTO;
import dds.gestores.GestorRegistros;
import dds.util.Pair;
import dds.enumerados.DiaSemana;
import dds.excepcionesLogicas.SolapamientoReservasException;
import java.awt.Cursor;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jlcla
 */
public class NuevaReservaPeriódica extends javax.swing.JFrame {
    private ReservaDTO rdto;
    DefaultTableModel modeloAnterior;
    PeriodicaItemDTO pi = new PeriodicaItemDTO();
    ReservasDelDocentePeriodica ventanaanterior;
    RegistrarReserva ventanavieja;
    /**
     * Creates new form NuevaReserva
     * @param rdto
     * @param modelo
     */
    public NuevaReservaPeriódica(ReservaDTO rdto, DefaultTableModel modelo, ReservasDelDocentePeriodica rp, RegistrarReserva rr) {
        initComponents();
        this.rdto=rdto;
        this.modeloAnterior=modelo;
        this.ventanaanterior=rp;
        this.ventanavieja=rr;
    }

    NuevaReservaPeriódica(ArrayList<String> itemsEditables, ReservaDTO rdto, DefaultTableModel modelo) {
        initComponents();
        this.rdto=rdto;
        this.modeloAnterior=modelo;
        DiaSemanaInterfaz.setSelectedItem(itemsEditables.get(0));
        HoraInicio.setText(itemsEditables.get(1));
        Duracion.setText(itemsEditables.get(2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DiaSemanaInterfaz = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        HoraInicio = new javax.swing.JFormattedTextField();
        Duracion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        Reservar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        NavegacionInicio = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        NavegacionNuevaReserva = new javax.swing.JLabel();
        NavegacionReservasPeriodicas = new javax.swing.JLabel();
        NavegacionReserva = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nueva Reserva Periódica"));

        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("(*)");

        jLabel14.setText("Dia de la semana");

        DiaSemanaInterfaz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("(*)");

        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("(*)");

        jLabel17.setText("Hora Inicio");

        jLabel19.setText("Duración");

        try {
            HoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        HoraInicio.setText(":");
        HoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraInicioActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("*La duración debe ser múltiplo de 30");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Cancelar.setBackground(new java.awt.Color(255, 255, 153));
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("HH:MM");

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Minutos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DiaSemanaInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(Buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cancelar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(DiaSemanaInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar)
                    .addComponent(Cancelar)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Resultados"));

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aula", "Tipo Aula", "Ubicación", "Capacidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaResultados);

        Reservar.setBackground(new java.awt.Color(153, 255, 153));
        Reservar.setText("Reservar");
        Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Reservar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reservar)
                .addContainerGap())
        );

        jLabel21.setText(">");

        NavegacionInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionInicio.setForeground(new java.awt.Color(51, 51, 255));
        NavegacionInicio.setText("Menú Bedel");
        NavegacionInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavegacionInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavegacionInicioMouseEntered(evt);
            }
        });

        jLabel22.setText(">");

        NavegacionNuevaReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionNuevaReserva.setText("Nueva Reserva Periódica");

        NavegacionReservasPeriodicas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionReservasPeriodicas.setForeground(new java.awt.Color(51, 51, 255));
        NavegacionReservasPeriodicas.setText("Reservas Periódicas");
        NavegacionReservasPeriodicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavegacionReservasPeriodicasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavegacionReservasPeriodicasMouseEntered(evt);
            }
        });

        NavegacionReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionReserva.setForeground(new java.awt.Color(51, 51, 255));
        NavegacionReserva.setText("Registrar Reservas");
        NavegacionReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavegacionReservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavegacionReservaMouseEntered(evt);
            }
        });

        jLabel20.setText(">");

        jLabel7.setText(">");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NavegacionInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NavegacionReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NavegacionReservasPeriodicas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NavegacionNuevaReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(61, 61, 61)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(NavegacionInicio))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NavegacionReserva)
                        .addComponent(jLabel20)
                        .addComponent(NavegacionReservasPeriodicas)
                        .addComponent(jLabel21)
                        .addComponent(NavegacionNuevaReserva)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraInicioActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        try {
            busqueda();
        } catch (CamposObligatoriosVaciosException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Campos vacios", JOptionPane.ERROR_MESSAGE);
        } catch (MultiploDe30Exception e){
            JOptionPane.showMessageDialog(null, "Error: duración debe ser múltiplo de 30", "Multiplo", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException e){
            JOptionPane.showMessageDialog(null, "Error: hora inválida", "Fecha", JOptionPane.ERROR_MESSAGE);
        } catch (HorarioFueraDeRangoException ex) {
            JOptionPane.showMessageDialog(null, "Error: horario fuera de rango, ingrese un horario entre las 6am y las 23pm", "Fecha", JOptionPane.ERROR_MESSAGE);
        } catch (DuracionExcedidaException ex) {
            JOptionPane.showMessageDialog(null, "Error: duración máxima de 4 horas excedida", "Fecha", JOptionPane.ERROR_MESSAGE);
        } catch (DuracionCeroException ex) {
            JOptionPane.showMessageDialog(null, "Error: duración inválida", "Fecha", JOptionPane.ERROR_MESSAGE);
        }  catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: formato invalido de duracion", "Fecha", JOptionPane.ERROR_MESSAGE);
        } catch (NoHayAulasDisponiblesException ex) {
            JOptionPane.showMessageDialog(null, "Error: no hay aulas disponibles con los criterios solicitados", "Fecha", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BuscarActionPerformed
    private void busqueda() throws CamposObligatoriosVaciosException, MultiploDe30Exception, HorarioFueraDeRangoException, DuracionExcedidaException, DuracionCeroException, NoHayAulasDisponiblesException{
        String mensaje="Error: hay uno o mas campos obligatorios (*) sin llenar: ";
        if (DiaSemanaInterfaz.getSelectedItem().toString().equals("<Seleccione>")) mensaje+="Dia de semana ";
        if (HoraInicio.getText().equals("  :  ")) mensaje+="hora de inicio ";
        if (Duracion.getText().equals("")) mensaje+="duracion";
        if (!mensaje.equals("Error: hay uno o mas campos obligatorios (*) sin llenar: ")) throw new CamposObligatoriosVaciosException(mensaje);
        
        if (Integer.parseInt(Duracion.getText())%30!=0) throw new MultiploDe30Exception();
        
        if (Integer.parseInt(Duracion.getText()) <= 0) throw new DuracionCeroException();
        
        String horastr = HoraInicio.getText();
        LocalTime hora = LocalTime.parse(horastr, DateTimeFormatter.ofPattern("HH:mm"));
        LocalTime horafin;
        pi.setHorario(hora);
        horafin = pi.horarioFin(hora, Integer.parseInt(Duracion.getText()));
        pi.setHoraFin(horafin);
        pi.setDia(DiaSemana.valueOf(this.DiaSemanaInterfaz.getSelectedItem().toString()));
        
        if( (hora.isAfter(LocalTime.parse("23:00")) || hora.isBefore(LocalTime.parse("06:00"))) ||
                (pi.getHoraFin().isAfter(LocalTime.parse("23:00")) || pi.getHoraFin().isBefore(LocalTime.parse("06:00"))) ) throw new HorarioFueraDeRangoException();
        
        if (Integer.parseInt(Duracion.getText())>240) throw new DuracionExcedidaException();
        Pair<List<AulaDTO>, List<ReservaDTO>> resultados= GestorRegistros.getInstance().listadoOpcionesDeAula(rdto, pi, rdto.getCantidadDeAlumnos(), rdto.getTipoAula());
        
        if (resultados.getElement0()==null && resultados.getElement1().isEmpty()) throw new NoHayAulasDisponiblesException();
        else if (resultados.getElement0()==null){
             //for (ReservaDTO r: resultados.getElement1()) System.out.print(r.getId());
            new MostrarReservasSolapadas(resultados.getElement1(), pi).setVisible(true);
           
        } 
        else llenarTabla(resultados.getElement0());
        
    }
    private void llenarTabla(List<AulaDTO> aulas) {
        DefaultTableModel modelo = new DefaultTableModel(new Object[][] {}, new String[] {
            "Aula", "Tipo Aula", "Ubicación", "Capacidad"
        }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hace que ninguna celda sea editable
            }
        };
        
        for (AulaDTO a : aulas) {
            Object[] aula = new Object[4];
            aula[0] = a.getId();
            aula[1] = rdto.getTipoAula();
            aula[2] = a.getUbicacion();
            aula[3] = a.getCapacidad();

            modelo.addRow(aula);
        }
        TablaResultados.setModel(modelo);
        
    }
    private void ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarActionPerformed
        int filaSeleccionada = TablaResultados.getSelectedRow(); // Obtener la fila seleccionada
        //System.out.println("Fila seleccionada: " + filaSeleccionada);
        int opcion;
        if (filaSeleccionada!=-1){ 
            opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de realizar la reserva?",
                "Confirmar reserva",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );
            if (opcion == JOptionPane.YES_OPTION) {
                try {
                    pi.setAula((int) TablaResultados.getValueAt(filaSeleccionada, 0));
                    GestorRegistros.getInstance().validarItems(rdto.getItemsPeriodica(),pi);
                    rdto.agregarItem(pi);
                    Object[] reserva = new Object[7];
                    reserva[0] = pi.getAula();
                    reserva[1] = TablaResultados.getValueAt(filaSeleccionada, 1).toString();
                    reserva[2] = pi.getDia().toString();
                    reserva[3] = pi.getHorario().toString();
                    LocalTime horafin;
                    horafin = pi.getHoraFin();
                    reserva[4] = horafin;
                    reserva[5] = TablaResultados.getValueAt(filaSeleccionada, 3).toString();
                    reserva[6] = TablaResultados.getValueAt(filaSeleccionada, 2).toString();
                    modeloAnterior.addRow(reserva);
                    this.dispose();
                    ventanaanterior.setVisible(true);
                } catch (SolapamientoReservasException ex) {
                   JOptionPane.showMessageDialog(null, "Error: la nueva reserva se solapa con una anterior", "Reserva", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else {
            JOptionPane.showMessageDialog(this, "No selecciono una reserva", "Error de seleccion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ReservarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que volver al Menú Reservas Del Docente Periodica?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            ventanaanterior.setVisible(true);
        }
    }//GEN-LAST:event_CancelarActionPerformed

    private void NavegacionReservasPeriodicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionReservasPeriodicasMouseClicked
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú de Reservas Periódicas?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            ventanaanterior.setVisible(true);
        }
    }//GEN-LAST:event_NavegacionReservasPeriodicasMouseClicked

    private void NavegacionReservasPeriodicasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionReservasPeriodicasMouseEntered
        NavegacionReservasPeriodicas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NavegacionReservasPeriodicasMouseEntered

    private void NavegacionReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionReservaMouseClicked
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú de Registrar Reservas?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            ventanavieja.setVisible(true);
        }
    }//GEN-LAST:event_NavegacionReservaMouseClicked

    private void NavegacionReservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionReservaMouseEntered
        NavegacionReserva.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NavegacionReservaMouseEntered

    private void NavegacionInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionInicioMouseClicked
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú Bedel?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();

            // Regresar al menú
            MenuBedel mb = new MenuBedel(this.rdto.getIdbedel());
            mb.setVisible(true);
        }
    }//GEN-LAST:event_NavegacionInicioMouseClicked

    private void NavegacionInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionInicioMouseEntered
        // Cambiar el cursor a mano
        NavegacionInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NavegacionInicioMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<String> DiaSemanaInterfaz;
    private javax.swing.JTextField Duracion;
    private javax.swing.JFormattedTextField HoraInicio;
    private javax.swing.JLabel NavegacionInicio;
    private javax.swing.JLabel NavegacionNuevaReserva;
    private javax.swing.JLabel NavegacionReserva;
    private javax.swing.JLabel NavegacionReservasPeriodicas;
    private javax.swing.JButton Reservar;
    private javax.swing.JTable TablaResultados;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
