/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dds.pantallas;

import dds.excepcionesInterfaz.FormatoEmailErroneoException;
import dds.excepcionesInterfaz.ContraseñasDifierenException;
import dds.excepcionesInterfaz.CamposObligatoriosVaciosException;
import dds.excepcionesInterfaz.LongitudesMaximasException;
import dds.dtos.BedelDTO;
import dds.excepcionesLogicas.BedelYaExisteException;
import dds.gestores.GestorBedel;
import dds.excepcionesLogicas.PoliticaDeContraseñaException;
import dds.enumerados.Turno;
import dds.gestores.GestorContraseña;
import java.awt.Cursor;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author augus
 */
public class RegistrarBedel extends javax.swing.JDialog {

    /**
     * Creates new form RegistrarBedel
     */
    public RegistrarBedel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        BotonRegistrar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CampoApellido = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();
        verPW = new javax.swing.JCheckBox();
        ListaTurno = new javax.swing.JComboBox<>();
        verCPW = new javax.swing.JCheckBox();
        CampoContrasena = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        CampoConfirmarContrasena = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CampoIdUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NavegacionMenuAdmin = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("(*)");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegistrarMouseClicked(evt);
            }
        });
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(255, 255, 153));
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registrar Bedel"));

        jLabel4.setText("Email");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Confirmar contraseña");

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("(*)");

        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("(*)");

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("(*)");

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("(*)");

        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("(*)");

        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("(*)");

        jLabel15.setText("La contraseña debe contener al menos:");

        jLabel16.setText("-8 caracteres");

        CampoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreActionPerformed(evt);
            }
        });

        jLabel17.setText("-Una mayúscula");

        jLabel18.setText("-2 caracteres especiales");

        jLabel19.setText("-Un dígito");

        CampoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEmailActionPerformed(evt);
            }
        });

        verPW.setText("Ver contraseña");
        verPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPWActionPerformed(evt);
            }
        });

        ListaTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Mañana", "Tarde", "Noche" }));
        ListaTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaTurnoActionPerformed(evt);
            }
        });

        verCPW.setText("Ver contraseña");
        verCPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCPWActionPerformed(evt);
            }
        });

        CampoContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoContrasenaActionPerformed(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("(*)");

        jLabel21.setText("idUsuario");

        jLabel1.setText("Apellido");

        CampoIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIdUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Turno en el que trabaja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ListaTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CampoApellido)
                                .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CampoContrasena)
                                .addComponent(CampoConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verPW, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verCPW, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ListaTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(CampoIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CampoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CampoConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(verPW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verCPW)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jLabel22.setText(">");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Registrar Bedel");

        NavegacionMenuAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionMenuAdmin.setForeground(new java.awt.Color(51, 51, 255));
        NavegacionMenuAdmin.setText("Menú Administrador");
        NavegacionMenuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavegacionMenuAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavegacionMenuAdminMouseEntered(evt);
            }
        });

        jLabel23.setText(">");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NavegacionMenuAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel22)
                    .addComponent(NavegacionMenuAdmin)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegistrar)
                    .addComponent(botonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreActionPerformed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void BotonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarMouseClicked
        // TODO add your handling code here:
        // public BedelDTO(int id, String nombre, String apellido, String email, String password, Turno turno) {
        try {
            registrar();
            limpiarCampos();
        } catch (CamposObligatoriosVaciosException ex) {
            //en el String se podria mostrar mas Info
            JOptionPane.showMessageDialog(null, "Error: hay uno o mas campos obligatorios (*) sin llenar", "registro", JOptionPane.ERROR_MESSAGE);
        } //asi, catch las otras excepciones
        catch (LongitudesMaximasException ex) {
            JOptionPane.showMessageDialog(null, "Error: longitud maxima de algun campo excedida", "registro", JOptionPane.ERROR_MESSAGE);
        } catch (ContraseñasDifierenException ex) {
            JOptionPane.showMessageDialog(null, "Error: la contraseña no coincide con la confirmacion", "registro", JOptionPane.ERROR_MESSAGE);
        } catch (PoliticaDeContraseñaException ex) {
            JOptionPane.showMessageDialog(null, "Error: la contraseña no cumple con las políticas establecidas", "registro", JOptionPane.ERROR_MESSAGE);
        } catch (BedelYaExisteException ex) {
            JOptionPane.showMessageDialog(null, "Error: ya existe el bedel con ese IdUsuario y se encuentra activo", "registro", JOptionPane.ERROR_MESSAGE);
        } catch (FormatoEmailErroneoException ex){
            JOptionPane.showMessageDialog(null, "Error: formato de email erróneo", "registro", JOptionPane.ERROR_MESSAGE);
        } catch (NoSuchAlgorithmException ex) {
            System.err.println("Error en el encriptado");
        } catch (InvalidKeySpecException ex) {
            System.err.println("Error en el encriptado");
        }
    }//GEN-LAST:event_BotonRegistrarMouseClicked

    private void registrar() throws CamposObligatoriosVaciosException, ContraseñasDifierenException, LongitudesMaximasException, PoliticaDeContraseñaException, BedelYaExisteException, NoSuchAlgorithmException, InvalidKeySpecException, FormatoEmailErroneoException {

        if ("<Seleccione>".equals(ListaTurno.getSelectedItem().toString())
                || "".equals(CampoIdUsuario.getText()) || "".equals(CampoNombre.getText()) || "".equals(CampoApellido.getText()) ||
                "".equals(CampoEmail.getText()) || "".equals(CampoContrasena.getText()) || "".equals(CampoConfirmarContrasena.getText())) {
            throw new CamposObligatoriosVaciosException();
        }
        
        
        //longitudes maximas
        if (CampoApellido.getText().length() > 50 
                || CampoIdUsuario.getText().length() > 50
                || CampoNombre.getText().length() > 50
                || CampoEmail.getText().length() > 80
                || CampoContrasena.getText().length() > 50
                || CampoConfirmarContrasena.getText().length() > 50) {
            throw new LongitudesMaximasException();
        }

        if (!CampoContrasena.getText().equals(CampoConfirmarContrasena.getText())) {
            throw new ContraseñasDifierenException();
        }
        
        
        if (!GestorContraseña.getInstance().validarMail(CampoEmail.getText())) throw new FormatoEmailErroneoException();
        
        BedelDTO bdto = new BedelDTO(1, //arbitrario en este caso
                CampoIdUsuario.getText(),
                CampoNombre.getText(),
                CampoApellido.getText(),
                CampoEmail.getText(),
                CampoContrasena.getText(),
                CampoConfirmarContrasena.getText(),
                Turno.valueOf(ListaTurno.getSelectedItem().toString())
        );

        GestorBedel.getInstance().registro(bdto);
        JOptionPane.showMessageDialog(null, "Éxito! Bedel registrado", "registro", JOptionPane.INFORMATION_MESSAGE);
    }

    private void CampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEmailActionPerformed

    private void CampoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoApellidoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas volver al Menú Administrador?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        // Verificar si el usuario eligió "Sí"
        if (respuesta == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();

            // Regresar al menú admin
            MenuAdmin ma = new MenuAdmin();
            ma.setVisible(true);
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void ListaTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaTurnoActionPerformed

    private void verPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPWActionPerformed
        if (evt.getSource() == verPW) {
            if (verPW.isSelected()) {
                // Si está seleccionado, mostrar la contraseña
                CampoContrasena.setEchoChar((char) 0);
            } else {
                // Si no está seleccionado, ocultar la contraseña
                CampoContrasena.setEchoChar('•');
            }
        }
    }//GEN-LAST:event_verPWActionPerformed

    private void verCPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCPWActionPerformed
        if (evt.getSource() == verCPW) {
            if (verCPW.isSelected()) {
                // Si está seleccionado, mostrar la contraseña
                CampoConfirmarContrasena.setEchoChar((char) 0);
            } else {
                // Si no está seleccionado, ocultar la contraseña
                CampoConfirmarContrasena.setEchoChar('•');
            }
        }
    }//GEN-LAST:event_verCPWActionPerformed

    private void CampoContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoContrasenaActionPerformed

    private void CampoIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIdUsuarioActionPerformed

    private void NavegacionMenuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionMenuAdminMouseClicked
                            int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú Administrador?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();

            // Regresar al menú 
            MenuAdmin ma = new MenuAdmin();
            ma.setVisible(true);
        }
    }//GEN-LAST:event_NavegacionMenuAdminMouseClicked

    private void NavegacionMenuAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionMenuAdminMouseEntered
        NavegacionMenuAdmin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NavegacionMenuAdminMouseEntered

     private void limpiarCampos(){
        this.CampoIdUsuario.setText("");
        this.CampoApellido.setText("");
        this.CampoNombre.setText("");
        this.CampoEmail.setText("");
        this.CampoContrasena.setText("");
        this.CampoConfirmarContrasena.setText("");
        this.ListaTurno.setSelectedItem("<Seleccione>");
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JTextField CampoApellido;
    private javax.swing.JPasswordField CampoConfirmarContrasena;
    private javax.swing.JPasswordField CampoContrasena;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoIdUsuario;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JComboBox<String> ListaTurno;
    private javax.swing.JLabel NavegacionMenuAdmin;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox verCPW;
    private javax.swing.JCheckBox verPW;
    // End of variables declaration//GEN-END:variables
}
