/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dds.pantallas;

import dds.excepcionesInterfaz.FormatoEmailErroneoException;
import dds.excepcionesInterfaz.CapacidadInvalidaException;
import dds.excepcionesInterfaz.CamposObligatoriosVaciosException;
import dds.excepcionesInterfaz.LongitudesMaximasException;
import dds.dtos.BedelDTO;
import dds.dtos.ReservaDTO;
import dds.entidades.Bedel;
import dds.enumerados.TipoAula;
import dds.enumerados.TipoPeriodo;
import dds.gestores.GestorBedel;
import dds.gestores.GestorContraseña;
import dds.gestores.GestorRegistros;
import java.awt.Cursor;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.Year;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jlcla
 */
public class RegistrarReserva extends javax.swing.JFrame {
    String idbedel;
    /**
     * Creates new form RegistrarReserva
     * @param usuario
     */
    public RegistrarReserva(String usuario) {
        initComponents();
        this.idbedel=usuario;
        //si termino el segundo cuatrimestre del 2025 entonces anular la reserva:
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) Periodo.getModel();
        if (LocalDate.now().isAfter(LocalDate.of(2025, 5, 1))){
            model.removeElement("1C");
            model.removeElement("ANUAL");
        }
        if (LocalDate.now().isAfter(LocalDate.of(2025, 9, 1))){
            model.removeElement("2C");
        }
        ArrayList<String> docentes = new ArrayList<>();
        docentes = GestorRegistros.getInstance().getDocentes();
        for (String docente: docentes){
            NombreDocente.addItem(docente);
        }
        ArrayList<String> catedras = new ArrayList<>();
        catedras = GestorRegistros.getInstance().getMaterias();
        for (String catedra: catedras){
            NombreCatedra.addItem(catedra);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cancelar = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        NombreCatedra = new javax.swing.JComboBox<>();
        TipoDeAula = new javax.swing.JComboBox<>();
        CantidadDeAlumnos = new javax.swing.JTextField();
        MailDeDocente = new javax.swing.JTextField();
        Periodo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        NombreDocente = new javax.swing.JComboBox<>();
        NavegacionReserva = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NavegacionInicio = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cancelar.setBackground(new java.awt.Color(255, 255, 153));
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registrar Reservas"));

        jLabel14.setText("Tipo de aula");

        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("(*)");

        NombreCatedra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>" }));
        NombreCatedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCatedraActionPerformed(evt);
            }
        });

        TipoDeAula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "MULTIMEDIOS", "INFORMÁTICA", "SIN RECURSOS" }));

        Periodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "1C", "2C", "ANUAL", "ESPORÁDICA" }));

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("(*)");

        jLabel3.setText("Nombre de cátedra");

        jLabel4.setText("Cantidad de alumnos");

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("(*)");

        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("(*)");

        jLabel5.setText("Mail de docente");

        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("(*)");

        jLabel6.setText("Tipo de reserva");

        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setText("(*)");

        jLabel18.setText("Docente");

        NombreDocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>" }));
        NombreDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TipoDeAula, 0, 167, Short.MAX_VALUE)
                            .addComponent(NombreCatedra, 0, 1, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(64, 64, 64)
                        .addComponent(NombreDocente, 0, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MailDeDocente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadDeAlumnos)
                    .addComponent(Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(CantidadDeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MailDeDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(NombreCatedra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(TipoDeAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        NavegacionReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionReserva.setText("Registrar Reservas");

        jLabel7.setText(">");

        NavegacionInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionInicio.setForeground(new java.awt.Color(51, 51, 255));
        NavegacionInicio.setText("Menú Bedel");
        NavegacionInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavegacionInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavegacionInicioMouseEntered(evt);
            }
        });

        jLabel16.setText(">");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Siguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cancelar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NavegacionInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NavegacionReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(315, 315, 315)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NavegacionReserva)
                    .addComponent(jLabel7)
                    .addComponent(NavegacionInicio)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Siguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        try {
            this.registro();
        } catch (CamposObligatoriosVaciosException e) {
            JOptionPane.showMessageDialog(null, "Error: hay uno o mas campos obligatorios (*) sin llenar", "registro", JOptionPane.ERROR_MESSAGE);
        } catch (LongitudesMaximasException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "registro", JOptionPane.ERROR_MESSAGE);
        } catch (CapacidadInvalidaException e){
            JOptionPane.showMessageDialog(null, "Error: capacidad de aulas fuera de rango", "registro", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error: ingrese una cantidad de alumnos valida", "registro", JOptionPane.ERROR_MESSAGE);
        } catch (FormatoEmailErroneoException ex){
            JOptionPane.showMessageDialog(null, "Error: formato de email erróneo", "registro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SiguienteActionPerformed
    private void registro() throws CamposObligatoriosVaciosException, LongitudesMaximasException, CapacidadInvalidaException, FormatoEmailErroneoException{
        if (
                NombreDocente.getSelectedItem().toString().equals("<Seleccione>")
                || CantidadDeAlumnos.getText().equals("")
                || MailDeDocente.getText().equals("")
                || NombreCatedra.getSelectedItem().toString().equals("<Seleccione>")
                || Periodo.getSelectedItem().toString().equals("<Seleccione>")
                || TipoDeAula.getSelectedItem().toString().equals("<Seleccione>")
            ) throw new CamposObligatoriosVaciosException();
        if ( (MailDeDocente.getText()).length()>80 ) throw new LongitudesMaximasException("Error: longitud del email excede los 80 caracteres");
        if (Integer.parseInt(CantidadDeAlumnos.getText())<0 || Integer.parseInt(CantidadDeAlumnos.getText())>200) throw new CapacidadInvalidaException();
        if (!GestorContraseña.getInstance().validarMail(MailDeDocente.getText())) throw new FormatoEmailErroneoException();
        TipoPeriodo periodo=null;
        String aux;
        aux=Periodo.getSelectedItem().toString();
        if (aux.equals("ANUAL")) periodo=TipoPeriodo.ANUAL;
        if (aux.equals("ESPORÁDICA")) periodo=null;
        if (aux.equals("1C")) periodo=TipoPeriodo.PRIMER_CUATRIMESTRE;
        else if (aux.equals("2C")) periodo=TipoPeriodo.SEGUNDO_CUATRIMESTRE;
        
        TipoAula aula=null;
        aux=TipoDeAula.getSelectedItem().toString();
        if(aux.equals("SIN RECURSOS")) aula=TipoAula.SINRECURSOS;
        else if (aux.equals("INFORMÁTICA")) aula=TipoAula.INFORMATICA;
        else if (aux.equals("MULTIMEDIOS")) aula=TipoAula.MULTIMEDIOS;
        ReservaDTO rdto = new ReservaDTO(
                1,
                MailDeDocente.getText(),
                Integer.parseInt(CantidadDeAlumnos.getText()),
                NombreCatedra.getSelectedItem().toString(),
                NombreDocente.getSelectedItem().toString(),
                aula,
                LocalDate.now(),
                Periodo.getSelectedItem().toString().equals("ESPORÁDICA"),
                idbedel,
                periodo,
                null,
                null
        );
        boolean a;
        a = Periodo.getSelectedItem().toString().equals("ESPORÁDICA");
        if (a){
            this.setVisible(false);
            ReservasDelDocenteEsporadica nuevoMenu = new ReservasDelDocenteEsporadica(this, rdto);
            nuevoMenu.setVisible(true);
        }else {
            this.setVisible(false);
            ReservasDelDocentePeriodica nuevoMenu = new ReservasDelDocentePeriodica(this, rdto);
            nuevoMenu.setVisible(true);
        }
    }
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú Bedel?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();

            // Regresar al menú 
            MenuBedel mb = new MenuBedel(this.idbedel);
            mb.setVisible(true);
        }
    }//GEN-LAST:event_CancelarActionPerformed

    private void NavegacionInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionInicioMouseClicked
                    int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú Bedel?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();

            // Regresar al menú 
            MenuBedel mb = new MenuBedel(this.idbedel);
            mb.setVisible(true);
        }
    }//GEN-LAST:event_NavegacionInicioMouseClicked

    private void NavegacionInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionInicioMouseEntered
        // Cambiar el cursor a mano
        NavegacionInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NavegacionInicioMouseEntered

    private void NombreDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreDocenteActionPerformed

    }//GEN-LAST:event_NombreDocenteActionPerformed

    private void NombreCatedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCatedraActionPerformed

    }//GEN-LAST:event_NombreCatedraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField CantidadDeAlumnos;
    private javax.swing.JTextField MailDeDocente;
    private javax.swing.JLabel NavegacionInicio;
    private javax.swing.JLabel NavegacionReserva;
    private javax.swing.JComboBox<String> NombreCatedra;
    private javax.swing.JComboBox<String> NombreDocente;
    private javax.swing.JComboBox<String> Periodo;
    private javax.swing.JButton Siguiente;
    private javax.swing.JComboBox<String> TipoDeAula;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
