/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dds.pantallas;

import dds.dtos.EsporadicaItemDTO;
import dds.dtos.PeriodicaItemDTO;
import dds.dtos.ReservaDTO;
import dds.enumerados.TipoPeriodo;
import dds.excepcionesLogicas.AulaNoEncontradoException;
import dds.excepcionesLogicas.BedelNoEncontradoException;
import dds.gestores.GestorBedel;
import dds.gestores.GestorRegistros;
import java.awt.Component;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.FocusTraversalPolicy;
import java.time.Duration;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jlcla
 */
public class ReservasDelDocentePeriodica extends javax.swing.JFrame {
    RegistrarReserva ventanaAnterior;
    ReservaDTO rdto;
    DefaultTableModel modelo=new DefaultTableModel(new Object[][] {}, new String[] {
            "Aula", "Tipo Aula", "Dia Semana", "Hora Inicio", "Hora Fin", "Capacidad", "Ubicacion"
        }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hace que ninguna celda sea editable
            }
        };
    /**
     * Creates new form ReservasDelDocente
     */
    public ReservasDelDocentePeriodica(RegistrarReserva rr, ReservaDTO rdto) {
        initComponents();
        this.ventanaAnterior=rr;
        this.rdto = rdto;
        nombreDocente.setText(rdto.getNombreapellidodocente());
        this.rdto.setItemsPeriodica(new ArrayList<PeriodicaItemDTO>());
        configurarTabulacion(); 
    }
    private void configurarTabulacion() {
        // Configuramos una política de tabulación personalizada
        setFocusTraversalPolicy(new FocusTraversalPolicy() {
            @Override
            public Component getComponentAfter(Container container, Component component) {
                if (component.equals(NuevaReserva)) return EliminarReserva;
                if (component.equals(EliminarReserva)) return Guardar;
                if (component.equals(Guardar)) return Cancelar;
                return NuevaReserva; // Vuelve al primero después del último
            }

            @Override
            public Component getComponentBefore(Container container, Component component) {
                if (component.equals(Cancelar)) return Guardar;
                if (component.equals(Guardar)) return EliminarReserva;
                if (component.equals(EliminarReserva)) return NuevaReserva;
                return Cancelar; // Vuelve al último antes del primero
            }

            @Override
            public Component getDefaultComponent(Container container) {
                return NuevaReserva; // Componente que recibe el foco al abrir la ventana
            }

            @Override
            public Component getFirstComponent(Container container) {
                return NuevaReserva; // Primer componente del ciclo
            }

            @Override
            public Component getLastComponent(Container container) {
                return Cancelar; // Último componente del ciclo
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevaReserva = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        EliminarReserva = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        nombreDocente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NavegacionInicio = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NavegacionReserva = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NavegacionReservasPeriodicas = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NuevaReserva.setText("Nueva Reserva");
        NuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaReservaActionPerformed(evt);
            }
        });

        Guardar.setBackground(new java.awt.Color(153, 255, 153));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Cancelar.setBackground(new java.awt.Color(255, 255, 153));
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        EliminarReserva.setBackground(new java.awt.Color(255, 153, 153));
        EliminarReserva.setText("Eliminar Reserva");
        EliminarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarReservaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Reservas Periódicas"));

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aula", "Tipo Aula", "Dia Semana", "Hora Inicio", "Hora Fin", "Capacidad", "Ubicación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaResultados);

        nombreDocente.setText("nombreDocente");

        jLabel1.setText("Reservas períodicas de: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreDocente)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreDocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        NavegacionInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionInicio.setForeground(new java.awt.Color(51, 51, 255));
        NavegacionInicio.setText("Menú Bedel");
        NavegacionInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavegacionInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavegacionInicioMouseEntered(evt);
            }
        });

        jLabel7.setText(">");

        NavegacionReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionReserva.setForeground(new java.awt.Color(51, 51, 255));
        NavegacionReserva.setText("Registrar Reservas");
        NavegacionReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NavegacionReservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavegacionReservaMouseEntered(evt);
            }
        });

        jLabel16.setText(">");

        NavegacionReservasPeriodicas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NavegacionReservasPeriodicas.setText("Reservas Periódicas");

        jLabel17.setText(">");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NavegacionInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NavegacionReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NavegacionReservasPeriodicas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NuevaReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EliminarReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                        .addComponent(Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NavegacionReserva)
                    .addComponent(jLabel16)
                    .addComponent(jLabel7)
                    .addComponent(NavegacionInicio)
                    .addComponent(NavegacionReservasPeriodicas)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar)
                    .addComponent(EliminarReserva)
                    .addComponent(NuevaReserva))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaReservaActionPerformed
        this.setVisible(false);
        new NuevaReservaPeriódica(rdto, modelo, this, ventanaAnterior).setVisible(true);
        TablaResultados.setModel(modelo);
    }//GEN-LAST:event_NuevaReservaActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        int opcion;
        opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de guardar la reserva?",
            "Confirmar guardado",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION && modelo.getRowCount()!=0) {
            try {
                GestorRegistros.getInstance().crearReserva(rdto);
                JOptionPane.showMessageDialog(null, "Éxito! Reserva registrada", "registro", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                ventanaAnterior.setVisible(true);
            } catch (Exception e) {
                
            }
            
        } else if (modelo.getRowCount()==0) JOptionPane.showMessageDialog(null, "Error: no hay reservas para guardar", "registro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_GuardarActionPerformed

    private void EliminarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarReservaActionPerformed
        int filaSeleccionada = TablaResultados.getSelectedRow();
        int opcion;
        if (filaSeleccionada!=-1){ 
            opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de eliminar la reserva?",
                "Confirmar eliminacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );
            if (opcion == JOptionPane.YES_OPTION) {
                DefaultTableModel modelo = (DefaultTableModel) TablaResultados.getModel();
                modelo.removeRow(filaSeleccionada);
                rdto.getItemsPeriodica().remove(filaSeleccionada);
            }
        }else {
            JOptionPane.showMessageDialog(this, "No selecciono una reserva", "Error de seleccion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EliminarReservaActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú Registrar Reserva?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            ventanaAnterior.setVisible(true);
        }
    }//GEN-LAST:event_CancelarActionPerformed

    private void NavegacionInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionInicioMouseClicked
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú Bedel?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            this.dispose();

            // Regresar al menú
            MenuBedel mb = new MenuBedel(this.rdto.getIdbedel());
            mb.setVisible(true);
        }
    }//GEN-LAST:event_NavegacionInicioMouseClicked

    private void NavegacionInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionInicioMouseEntered
        // Cambiar el cursor a mano
        NavegacionInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NavegacionInicioMouseEntered

    private void NavegacionReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionReservaMouseClicked
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas volver al Menú Registrar Reserva?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            ventanaAnterior.setVisible(true);
        }
    }//GEN-LAST:event_NavegacionReservaMouseClicked

    private void NavegacionReservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavegacionReservaMouseEntered
        NavegacionReserva.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NavegacionReservaMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton EliminarReserva;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel NavegacionInicio;
    private javax.swing.JLabel NavegacionReserva;
    private javax.swing.JLabel NavegacionReservasPeriodicas;
    private javax.swing.JButton NuevaReserva;
    private javax.swing.JTable TablaResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreDocente;
    // End of variables declaration//GEN-END:variables
}
